mem_py/login/urls.py
from django.urls import path
from . import views

app_name='login'
urlpatterns = [
    path("",views.loginPage,name='login'),
    path("register",views.registerPage,name='register'),
]

mem_py/mem_py/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('login/',include('login.urls')),
    path('',include('menu.urls')),
]

mem_py/menu/urls.py
from django.urls import path
from . import views

app_name='menu'
urlpatterns = [
    path("",views.menuPage,name='menu'),
    path("logout",views.logoutPage,name='logout')
]

mem_py/login/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class UserProfile(User):
    level=models.SmallIntegerField(default=1)
    coincidences=models.SmallIntegerField(default=2)
    token=models.CharField(default='img',max_length=3)
    victory_text=models.CharField(default="Ganaste!",max_length=100)
    defeat_text=models.CharField(default="Perdiste!",max_length=100)
    

mem_py/menu/models.py
from django.db import models

# Create your models here.

mem_py/login/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm,AuthenticationForm
from .models import UserProfile

# Create your forms here 

class LoginForm(AuthenticationForm):
    def __init__(self, request, *args, **kwargs):
        super().__init__(self, request, *args, **kwargs)
        self.fields['username'].widget.attrs.update({'placeholder':'Nombre de Usuario'})
        self.fields['password'].widget.attrs.update({'placeholder':'Contraseña'})        
        self.error_messages['invalid_login']="Contraseña o Usuario incorrecto"
        for fieldname in ['username','password']:
            self.fields[fieldname].help_text = None
            self.fields[fieldname].label=""
    class Meta:
        model= UserProfile
        fields=[
            "username",
            "password",
        ]

class RegisterForm(UserCreationForm):

    def __init__(self, *args, **kwargs):
        super(UserCreationForm, self).__init__(*args, **kwargs)
        self.fields['username'].widget.attrs.update({'placeholder':'Nombre de Usuario'})
        self.fields['email'].widget.attrs.update({'placeholder':'Email'})
        self.fields['password1'].widget.attrs.update({'placeholder':'Contraseña'})        
        self.fields['password2'].widget.attrs.update({'placeholder':'Repetir Contraseña'})
        self.error_messages["password_mismatch"]="Las contraseñas no coinciden"
        for fieldname in ['username','email','password1', 'password2']:
            self.fields[fieldname].help_text = None
            self.fields[fieldname].label=""

    class Meta:
        model= UserProfile
        fields=[
            "username",
            "email",
            "password1",
            "password2",
        ]

mem_py/login/views.py
from django.shortcuts import render,redirect
from django.contrib.auth import authenticate,login
from .forms import RegisterForm,LoginForm

# Create your views here.

def loginPage(request):
    form=LoginForm(request.POST or None)
    print(form.errors)
    if form.is_valid(): 
        username = form.cleaned_data.get("username")
        password = form.cleaned_data.get('password')
        user= authenticate(request,username=username,password=password)
        if user:
            login(request, user)
            return redirect('menu:menu')

    return render(request,'login/login.html',{"form":form})


def registerPage(request):
    register=RegisterForm(request.POST or None)
    if register.is_valid():
        register.save()
        return redirect('login:login')
    return render(request,'login/register.html',{"form":register})

mem_py/menu/views.py
from django.shortcuts import redirect, render
from django.contrib.auth.decorators import login_required
from django.contrib.auth import logout
# Create your views here.

@login_required(login_url='login:login')
def menuPage(request):
    return render(request,'menu/menu.html',{})

@login_required(login_url='login:login')
def logoutPage(request):
    logout(request)
    return redirect('login:login')

mem_py/login/templates/login/base.html
{% load static %}
<!DOCTYPE html>
<html lang="es">
<head>
    <link href={% static 'login.css' %} rel='stylesheet'>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Mem_py</title>
</head>
<body>
    {% block body %}
    {% endblock body %}
    
</body>
</html>

mem_py/login/templates/login/login.html
{% extends 'login/base.html' %}

{% block body %}
    <div class="container">
        <h1 id="Title">MEMPY</h1>
        <form method="POST">
            {% csrf_token %}
            {% for field in form %}
                    {{ field }}
                    {% if field.help_text %}
                    <p class="help">{{ field.help_text|safe }}</p>
                    {% endif %}
            {% endfor %}
            {{ form.non_field_errors}}
            <input type='submit' value='Iniciar sesion' id='login_button'>
        </form>
        <h5 id="registerBanner"> No tenes cuenta? <a  href={% url 'login:register' %}>Registrate</a></h5>    
    </div>

{% endblock body %}

mem_py/login/templates/login/register.html
{% extends 'login/base.html' %}

{% block body %}
    
    <div class="container">
        <h1 id="Title">Registrarse</h1>
        <form action="" method="POST">
            {% csrf_token %}
             {% for field in form %}
                    {{ field }}
                    {% if field.help_text %}
                    <p class="help">{{ field.help_text|safe }}</p>
                    {% endif %}
            {% endfor %}
            {{ form.errors  }}
            <input type='submit' value='Registrarse' id='login_button'>
        </form>
         <h5 id="registerBanner">Ya tienes cuenta? <a  href={% url 'login:login' %}>Inicia Sesion</a></h5>
    </div>

{% endblock body %}

mem_py/menu/templates/menu/menu.html
{% load static %}
<!DOCTYPE html>
<html lang="es">
<head>
    <link href={% static 'menu.css' %} rel='stylesheet'>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Mempy</title>
</head>
<body>
    <nav>
        <h1 id="menu">Mempy</h1>
        <h2 id="welcome"> Hola, {{ request.user|capfirst }}  <a href={% url 'menu:logout' %}>Cerrar Sesion </a></h2>
    </nav>
    <div class="container">
        <div id='container-score'>
        <h4 id="score-banner">Score</h4>
        </div>
        <div id='container-game'>
        <h4 id="game-banner">Play!</h4>
        </div>
        <div id='container-config'>
        <h4 id="config-banner">Configuration</h4>
        </div>
    </div>
</body>
</html>